/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatalogoDeLocacaoRouteImport } from './routes/catalogo-de-locacao'
import { Route as IndexRouteImport } from './routes/index'

const CatalogoDeLocacaoRoute = CatalogoDeLocacaoRouteImport.update({
  id: '/catalogo-de-locacao',
  path: '/catalogo-de-locacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo-de-locacao': typeof CatalogoDeLocacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo-de-locacao': typeof CatalogoDeLocacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo-de-locacao': typeof CatalogoDeLocacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalogo-de-locacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogo-de-locacao'
  id: '__root__' | '/' | '/catalogo-de-locacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoDeLocacaoRoute: typeof CatalogoDeLocacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalogo-de-locacao': {
      id: '/catalogo-de-locacao'
      path: '/catalogo-de-locacao'
      fullPath: '/catalogo-de-locacao'
      preLoaderRoute: typeof CatalogoDeLocacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoDeLocacaoRoute: CatalogoDeLocacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
